### ISSUE TITLE
failing build with make release

### ISSUE THREAD

**Issue by mathias-goebel** [etcd-io/auger#156]
```sh
> make release
[…]
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
make: *** [/go/src/github.com/etcd-io/auger/Makefile:67: release-docker-build] Error 1
make: *** [Makefile:55: release] Error 2
```
but works as expected with `-buildvcs=false` added to `Makefile` line 67.

**Comment by jmhbnz** [comment]
I believe the issue is the wrong docker image being used in the `make release` recipe.  The following diff for `Makefile` I believe fixes it:

```diff
-               golang:$(GO_VERSION) \
-               /bin/bash -c "make -f /go/src/$(PKG)/Makefile release-docker-build GOARCH=$(GOARCH) GOOS=$(GOOS) CGO_ENABLED=$(CGO_ENABLED)"
+               docker.io/golang:$(GO_VERSION)-alpine \
+               sh -c "make -f /go/src/$(PKG)/Makefile release-docker-build GOARCH=$(GOARCH) GOOS=$(GOOS) CGO_ENABLED=$(CGO_ENABLED)"
```

Would you mind testing with this patch applied and confirming?

**Comment by mathias-goebel** [comment]
sorry, there is no `make` in docker.io/golang:$(GO_VERSION)-alpine

**Comment by jmhbnz** [comment]
> sorry, there is no `make` in docker.io/golang:$(GO_VERSION)-alpine

Thanks for checking.  Given we are releasing via goreleaser with config in `.goreleaser` I think we can simply drop those two Makefile recipes (`make release` and `make release-docker-build`).  We still have `make build` for creating binaries locally when desired.

If you have capacity please feel free to update your open pr to simply remove the two recipes.

**Comment by mathias-goebel** [comment]
well, then it might be more urgent to adjust the installation instructions in README.md. I will update my PR in accordance.
