### ISSUE TITLE
Add `make verify` target for running static analysis checks

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/auger#31]
Recently in https://github.com/etcd-io/auger/pull/30 we introduced a new github actions workflow for running `golangci-lint` checks when new pr's are opened.

We should make this easy to run locally by adding a new `Makefile` recipe called `verify` to make it easy to do the same locally.

A simplistic example to base off would be https://github.com/etcd-io/bbolt/blob/main/Makefile#L38-L40.

**Comment by henrybear327** [comment]
Hello @jmhbnz, 

I would like to work on this issue :) 

Thank you!

Henry
